name: Auto Assign Fixed Reviewer

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewer based on author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('=== DEBUG INFO ===');
            console.log('PR Author:', context.payload.pull_request.user.login);
            console.log('Repository:', context.repo.owner + '/' + context.repo.repo);
            console.log('PR Number:', context.payload.pull_request.number);
            
            const author = context.payload.pull_request.user.login;
            let reviewer = null;

            if (author === "morepudding") {
              reviewer = "everythinn";
            } else if (author === "everythinn") {
              reviewer = "morepudding";
            } else {
              // Si l'auteur n'est ni morepudding ni everythinn, assigner everythinn par défaut
              console.log(`Author "${author}" not in predefined list, assigning default reviewer`);
              reviewer = "everythinn";
            }

            console.log('Selected reviewer:', reviewer);

            if (reviewer) {
              try {
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                  reviewers: [reviewer],
                });
                console.log(`✅ Successfully assigned ${reviewer} as reviewer`);
              } catch (error) {
                console.error('❌ Error assigning reviewer:', error.message);
                console.error('Error details:', error);
                throw error;
              }
            } else {
              console.log("ℹ️ No matching reviewer for author:", author);
            }
